http:
  port: "8081"
  readtimeout: "40000"

##American Flights Config
american:
  host: "training4-american-api.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "![scbVe9hdLC+fqLuJmLoDWppBImtTSqxHPA8NSDktS90cFLYyVy0/WA==]"
  client_secret: "![vT2NJW7b4VFp48io5hpptg89XyTEOKHpbIAfUvvCp9hw2dub8D7XIg==]"
  
##United Flights Config
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
##Delta Flights Config
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"
  
##Weather data
USWeather:
  host: "graphical.weather.gov"
  port: "443"
  